<?php
/**
 * @file
 * This file contains all Drupal hooks for the module other than any
 * node hooks and block hooks. Those go in the [module name].chado_node.inc file
 * and [module_name].blocks.inc respectively
 *
 * @ingroup legume_stock
 */

require_once('includes/legume_stock.chado_node.inc');

function legume_stock_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path('module', 'legume_stock');

  $items = array(
    'tripal_stock_base' => array(
      'variables' => array('node' => NULL),
      'template' => 'tripal_legume_stock_base',
      'path' => "$path/theme/templates",
    ),

  );

  return $items;
}//legume_stock_theme


/**
  * hook_form_alter
  */
function legume_stock_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && strstr($form['#id'], 'stock')) {
    // Set form validator
    $form['#validate'][] = 'legume_stock_form_validate';
    
    $default_collection = '- Any -';
    $new_options = array('0' => $default_collection);
    $sql = "SELECT name FROM {stockcollection} ORDER BY name";
    $result = chado_query($sql);
    foreach ($result as $r) {
      $new_options[$r->name] = $r->name;
    }

    // Add a collection dropdown
    if (count($new_options) > 1) {
      $collection_element = array(
        '#type'          => 'select',
        '#title'         => t('Collection'),
        '#options'       => $new_options,
        '#default_value' => $default_collection,
      );

      $form = array_slice($form, 0, 2, true) 
             + array('collection' => $collection_element)
             + array_slice($form, 2, count($form) - 1, true) ;
    }
    
    // Change default value for submit button
    $form['submit']['#value'] = 'Search';
  }
}//legume_stock_form_alter


function legume_stock_views_pre_render($view) {
  if ($view->name=='stock_search') { // because this is not a module...
  
    if (strstr($view->name, 'stocks')) {  // Report # stocks found before table
      if (isset($view->query->pager)) {
        $view->attachment_before = "<p><b>Found " . $view->query->pager->get_total_items() . " stocks</b></p>";
        
        $view->set_items_per_page('20');
      }
    }
  }

  if (isset($view->exposed_raw_input['name'])) {
    $search_term = $view->exposed_raw_input['name'];
  }
}//legume_qtl_views_pre_render


/**
  * Form validator for search form. 
  * Use this to trim whitespace from text fields.
  */
function legume_stock_form_validate($form, &$form_state) {
  // trim whitespace from all text fields;
  if (isset($form_state['values']['name']))
    $form_state['values']['name'] = trim($form_state['values']['name']);
}//legume_stock_form_validate


/**
  * hook_views_default_views_alter()
  * Alter the default tripal_stock view.
  */
function legume_stock_views_default_views_alter(&$views) {
  $handler =& $views['tripal_stock_user_stocks']->display['default']->handler;
  
  // Remove "uniquename from results table
  $handler->display->display_options['fields']['uniquename']['exclude'] = 1;
}//legume_stock_views_default_views_alter


/**
  * hook_views_query_alter()
  * Alter the search query before executing.
  */
function legume_stock_views_query_alter(&$view, &$query) {
//drupal_set_message("QUERY before:\n<pre>".print_r($query, true)."</pre>");
//drupal_set_message("EXPOSED INPUT:\n<pre>".print_r($view->exposed_input, true)."</pre>");

  if ($query->base_table != 'stock_search') {
    // Because this is not actually a module...
    return;
  }
  
  // Filter by collection
  if (isset($view->exposed_input['collection'])
        && $view->exposed_input['collection'] != '0') {
        
    // Add collection to where clause
    $query->where[] = array(
      'conditions' => array(
        array(
          'field'    => 'collection',
          'value'    => '%'.$view->exposed_input['collection'].'%',
          'operator' => 'LIKE',
        ),
      ),
      'args' => array(),
      'type' => 'AND',
    );
  }//collection selected

  // Only want one of each stock found
  $query->set_distinct(true, true);

/*
  // Default: order by stock name
  $query->orderby[0] = array(
    'field' => 'stock_name',
    'direction' => 'ASC',
  );
*/

//drupal_set_message("QUERY AFTER MODIFICATION:\n<pre>".print_r($query, true)."</pre>");
}//legume_stock_views_query_alter

